addons:
  postgresql: "9.6"
services:
  - postgresql

language: go

go:
    - 1.14

install:
    - go get -u golang.org/x/lint/golint
    - go get -u github.com/mattn/goveralls

script:
    - make all check GO_BUILDFLAGS="-mod vendor"
    - $HOME/gopath/bin/goveralls -coverprofile=build/cover.out -service=travis-ci
